name: Test & Build
on: [push, pull_request]
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    services:
      db:
        image: postgres #:13.3-alpine
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: anorm-async
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ANORM_ASYNC_DB_HOST: db

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: mill
      - uses: coursier/cache-action@v6
      - run: mill __.test
